#include "save_state.h"
#include "state.h"
#include "sprites.h"
#include "../snes/ppu.h"
#include "../snes/hardware.h"
#include "../snes/dma.h"
#include <cstdio>
#include <cstring>
#include <cstdarg>
#include <cstdlib>

// External references
extern PPURegisters ppu;
extern CPU65816 cpu;
extern GlobalState shadow;
extern StateMachine state_machine;
extern SNESPalette shadow_palette;
extern OAMBuffer oam_buffer;
extern SpriteTables sprite_tables;
extern uint8 vram[];
extern uint8 cgram[];
extern uint8 wram_low[];
extern uint8 wram_extended[];
extern DMAChannel dma_channels[5];

// ------------------------------------------------------------------
// Simple helpers: write/read key-value pairs
// ------------------------------------------------------------------
static void write_section(FILE* f, const char* name) {
    fprintf(f, "[%s]\n", name);
}

static void write_kv(FILE* f, const char* key, const char* fmt, ...) {
    fprintf(f, "%s=", key);
    va_list args;
    va_start(args, fmt);
    vfprintf(f, fmt, args);
    va_end(args);
    fprintf(f, "\n");
}

// Compute a simple checksum over a memory region
static uint32 compute_checksum(const uint8* data, uint32 size) {
    uint32 sum = 0;
    for (uint32 i = 0; i < size; i++) {
        sum = (sum << 1) ^ data[i];
    }
    return sum;
}

// ------------------------------------------------------------------
// save_state_to_file: Write game state to text file
// ------------------------------------------------------------------
bool save_state_to_file(const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) {
        fprintf(stderr, "Error: Cannot write state to %s\n", filename);
        return false;
    }

    fprintf(f, "# Zelda: A Link to the Past — Game State Dump\n");
    fprintf(f, "# Generated by headless renderer\n\n");

    // --- CPU state ---
    write_section(f, "cpu");
    write_kv(f, "A", "%04X", cpu.a);
    write_kv(f, "X", "%04X", cpu.x);
    write_kv(f, "Y", "%04X", cpu.y);
    write_kv(f, "SP", "%04X", cpu.sp);
    write_kv(f, "DP", "%04X", cpu.dp);
    write_kv(f, "DB", "%02X", cpu.db);
    write_kv(f, "PB", "%02X", cpu.pb);
    write_kv(f, "PC", "%04X", cpu.pc);
    write_kv(f, "emulation", "%d", cpu.emulation ? 1 : 0);
    fprintf(f, "\n");

    // --- PPU registers ---
    write_section(f, "ppu");
    write_kv(f, "INIDISP", "%02X", ppu.inidisp);
    write_kv(f, "OBJSEL", "%02X", ppu.objsel);
    write_kv(f, "BGMODE", "%02X", ppu.bgmode);
    write_kv(f, "MOSAIC", "%02X", ppu.mosaic);
    write_kv(f, "BG1HOFS", "%04X", ppu.bg1hofs);
    write_kv(f, "BG1VOFS", "%04X", ppu.bg1vofs);
    write_kv(f, "BG2HOFS", "%04X", ppu.bg2hofs);
    write_kv(f, "BG2VOFS", "%04X", ppu.bg2vofs);
    write_kv(f, "BG3HOFS", "%04X", ppu.bg3hofs);
    write_kv(f, "BG3VOFS", "%04X", ppu.bg3vofs);
    write_kv(f, "TM", "%02X", ppu.tm);
    write_kv(f, "TS", "%02X", ppu.ts);
    write_kv(f, "VMAIN", "%02X", ppu.vram_ctrl);
    write_kv(f, "VRAM_ADDR", "%04X", ppu.vram_addr);
    write_kv(f, "CGADD", "%02X", ppu.cgadd);
    write_kv(f, "NMITIMEN", "%02X", ppu.nmitimen);
    fprintf(f, "\n");

    // --- Memory checksums (don't dump all 64KB — just checksums) ---
    write_section(f, "memory");
    write_kv(f, "VRAM_checksum", "%08X", compute_checksum(vram, VRAM_SIZE));
    write_kv(f, "CGRAM_checksum", "%08X", compute_checksum(cgram, CGRAM_SIZE));
    write_kv(f, "WRAM_LOW_checksum", "%08X", compute_checksum(wram_low, WRAM_LOW_SIZE));
    write_kv(f, "WRAM_EXT_checksum", "%08X", compute_checksum(wram_extended, WRAM_EXTENDED_SIZE));

    // VRAM non-zero byte count
    uint32 vram_nonzero = 0;
    for (uint32 i = 0; i < VRAM_SIZE; i++) {
        if (vram[i] != 0) vram_nonzero++;
    }
    write_kv(f, "VRAM_nonzero_bytes", "%u", vram_nonzero);

    uint32 cgram_nonzero = 0;
    for (uint32 i = 0; i < CGRAM_SIZE; i++) {
        if (cgram[i] != 0) cgram_nonzero++;
    }
    write_kv(f, "CGRAM_nonzero_bytes", "%u", cgram_nonzero);
    fprintf(f, "\n");

    // --- Shadow state ---
    write_section(f, "shadow");
    write_kv(f, "game_mode", "%02X", shadow.game_mode);
    write_kv(f, "main_screen", "%02X", shadow.main_screen);
    write_kv(f, "sub_screen", "%02X", shadow.sub_screen);
    write_kv(f, "bg_mode", "%02X", shadow.bg_mode);
    write_kv(f, "nmi_flag", "%02X", shadow.nmi_flag);
    write_kv(f, "palette_dirty", "%02X", shadow.palette_dirty);
    write_kv(f, "frame_counter", "%02X", shadow.frame_counter);
    write_kv(f, "scroll_bg1_h", "%04X", shadow.scroll_bg1_h);
    write_kv(f, "scroll_bg1_v", "%04X", shadow.scroll_bg1_v);
    write_kv(f, "scroll_bg2_h", "%04X", shadow.scroll_bg2_h);
    write_kv(f, "scroll_bg2_v", "%04X", shadow.scroll_bg2_v);
    write_kv(f, "joypad1_held", "%04X", shadow.joypad1_held);
    write_kv(f, "joypad1_new", "%04X", shadow.joypad1_new);
    fprintf(f, "\n");

    // --- State machine ---
    write_section(f, "state_machine");
    write_kv(f, "current_state", "%02X", static_cast<uint8>(state_machine.current_state));
    write_kv(f, "next_state", "%02X", static_cast<uint8>(state_machine.next_state));
    write_kv(f, "sub_state", "%02X", state_machine.sub_state);
    write_kv(f, "transition_counter", "%02X", state_machine.transition_counter);
    fprintf(f, "\n");

    // --- DMA channels ---
    write_section(f, "dma");
    for (int ch = 0; ch < 5; ch++) {
        char key[32];
        snprintf(key, sizeof(key), "ch%d_mode", ch);
        write_kv(f, key, "%02X", dma_channels[ch].mode);
        snprintf(key, sizeof(key), "ch%d_bbus", ch);
        write_kv(f, key, "%02X", dma_channels[ch].bbus_addr);
        snprintf(key, sizeof(key), "ch%d_src", ch);
        write_kv(f, key, "%06X", dma_channels[ch].src_addr);
        snprintf(key, sizeof(key), "ch%d_size", ch);
        write_kv(f, key, "%04X", dma_channels[ch].size);
    }
    fprintf(f, "\n");

    fclose(f);
    printf("State saved to %s\n", filename);
    return true;
}

// ------------------------------------------------------------------
// load_state_from_file: Read game state from text file (partial)
//
// Note: This only restores scalar registers, not full memory dumps.
// For full state restore, memory arrays would need binary save.
// ------------------------------------------------------------------
bool load_state_from_file(const char* filename) {
    FILE* f = fopen(filename, "r");
    if (!f) {
        fprintf(stderr, "Error: Cannot read state from %s\n", filename);
        return false;
    }

    char line[256];
    char current_section[64] = "";

    while (fgets(line, sizeof(line), f)) {
        // Skip comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\0') continue;

        // Section header
        if (line[0] == '[') {
            char* end = strchr(line, ']');
            if (end) {
                *end = '\0';
                strncpy(current_section, line + 1, sizeof(current_section) - 1);
            }
            continue;
        }

        // Parse key=value
        char* eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';
        char* key = line;
        char* val = eq + 1;

        // Remove trailing newline
        char* nl = strchr(val, '\n');
        if (nl) *nl = '\0';

        uint32 u32_val = 0;
        uint16 u16_val = 0;
        uint8 u8_val = 0;

        if (strlen(val) <= 4) {
            u16_val = (uint16)strtoul(val, nullptr, 16);
            u8_val = (uint8)u16_val;
        } else {
            u32_val = strtoul(val, nullptr, 16);
        }

        // Apply based on section
        if (strcmp(current_section, "ppu") == 0) {
            if (strcmp(key, "INIDISP") == 0) ppu.inidisp = u8_val;
            else if (strcmp(key, "OBJSEL") == 0) ppu.objsel = u8_val;
            else if (strcmp(key, "BGMODE") == 0) ppu.bgmode = u8_val;
            else if (strcmp(key, "TM") == 0) ppu.tm = u8_val;
            else if (strcmp(key, "TS") == 0) ppu.ts = u8_val;
        } else if (strcmp(current_section, "shadow") == 0) {
            if (strcmp(key, "game_mode") == 0) shadow.game_mode = u8_val;
            else if (strcmp(key, "main_screen") == 0) shadow.main_screen = u8_val;
            else if (strcmp(key, "bg_mode") == 0) shadow.bg_mode = u8_val;
            else if (strcmp(key, "scroll_bg1_h") == 0) shadow.scroll_bg1_h = u16_val;
            else if (strcmp(key, "scroll_bg1_v") == 0) shadow.scroll_bg1_v = u16_val;
        } else if (strcmp(current_section, "state_machine") == 0) {
            if (strcmp(key, "current_state") == 0)
                state_machine.current_state = static_cast<GameState>(u8_val);
            else if (strcmp(key, "next_state") == 0)
                state_machine.next_state = static_cast<GameState>(u8_val);
        }
    }

    fclose(f);
    printf("State loaded from %s\n", filename);
    return true;
}

// ------------------------------------------------------------------
// save_state_with_screenshot: Save state + PPM side by side
// ------------------------------------------------------------------
bool save_state_with_screenshot(const char* state_file, const char* ppm_file) {
    // Save state
    if (!save_state_to_file(state_file)) return false;
    // Screenshot must be saved externally (renderer owns framebuffer)
    printf("State saved: %s (screenshot: %s)\n", state_file, ppm_file);
    return true;
}

// ------------------------------------------------------------------
// print_state_summary: Print key state values to stdout
// ------------------------------------------------------------------
void print_state_summary(void) {
    printf("=== Game State Summary ===\n");
    printf("  State machine: current=%d next=%d sub=%d\n",
           (int)state_machine.current_state,
           (int)state_machine.next_state,
           state_machine.sub_state);
    printf("  Game mode: 0x%02X\n", shadow.game_mode);
    printf("  Main screen: 0x%02X\n", shadow.main_screen);
    printf("  BG mode: %d\n", shadow.bg_mode);
    printf("  Scroll BG1: (%u, %u)\n", shadow.scroll_bg1_h, shadow.scroll_bg1_v);
    printf("  Frame counter: %u\n", shadow.frame_counter);

    // VRAM usage
    uint32 vram_used = 0;
    for (uint32 i = 0; i < VRAM_SIZE; i++) {
        if (vram[i] != 0) vram_used++;
    }
    printf("  VRAM: %u / %u bytes used (%.1f%%)\n",
           vram_used, VRAM_SIZE, 100.0f * vram_used / VRAM_SIZE);

    // CGRAM usage
    uint32 cgram_used = 0;
    for (uint32 i = 0; i < CGRAM_SIZE; i++) {
        if (cgram[i] != 0) cgram_used++;
    }
    printf("  CGRAM: %u / %u bytes used\n", cgram_used, CGRAM_SIZE);

    // OAM active sprites
    int active_sprites = 0;
    for (int i = 0; i < MAX_SPRITES; i++) {
        if (oam_buffer.entries[i].y != 0xF0 && oam_buffer.entries[i].y != 0) {
            active_sprites++;
        }
    }
    printf("  Active sprites: %d / %d\n", active_sprites, MAX_SPRITES);
    printf("===========================\n");
}
